In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

from matplotlib import pyplot as plt

In [2]:
data = pd.read_csv('data.csv')
data.head()

sex          age  suicides_no  population  suicides/100k pop  \
0    male  15-24 years           21      312900               6.71   
1    male  35-54 years           16      308000               5.19   
2  female  15-24 years           14      289700               4.83   
3    male    75+ years            1       21800               4.59   
4    male  25-34 years            9      274300               3.28   

  country-year  HDI for year  gdp_for_year ($)   gdp_per_capita ($)  \
0  Albania1987           NaN      2,156,624,900                 796   
1  Albania1987           NaN      2,156,624,900                 796   
2  Albania1987           NaN      2,156,624,900                 796   
3  Albania1987           NaN      2,156,624,900                 796   
4  Albania1987           NaN      2,156,624,900                 796   

        generation  
0     Generation X  
1           Silent  
2     Generation X  
3  G.I. Generation  
4          Boomers

In [3]:
data.describe(include='all')

sex          age   suicides_no    population  suicides/100k pop  \
count   27820        27820  27820.000000  2.782000e+04       27820.000000   
unique      2            6           NaN           NaN                NaN   
top      male  35-54 years           NaN           NaN                NaN   
freq    13910         4642           NaN           NaN                NaN   
mean      NaN          NaN    242.574407  1.844794e+06          12.816097   
std       NaN          NaN    902.047917  3.911779e+06          18.961511   
min       NaN          NaN      0.000000  2.780000e+02           0.000000   
25%       NaN          NaN      3.000000  9.749850e+04           0.920000   
50%       NaN          NaN     25.000000  4.301500e+05           5.990000   
75%       NaN          NaN    131.000000  1.486143e+06          16.620000   
max       NaN          NaN  22338.000000  4.380521e+07         224.970000   

             country-year  HDI for year  gdp_for_year ($)   \
count               27820   8364.000000              27820   
unique               2321           NaN               2321   
top     United States2007           NaN     22,165,932,063   
freq                   12           NaN                 12   
mean                  NaN      0.776601                NaN   
std                   NaN      0.093367                NaN   
min                   NaN      0.483000                NaN   
25%                   NaN      0.713000                NaN   
50%                   NaN      0.779000                NaN   
75%                   NaN      0.855000                NaN   
max                   NaN      0.944000                NaN   

        gdp_per_capita ($)    generation  
count         27820.000000         27820  
unique                 NaN             6  
top                    NaN  Generation X  
freq                   NaN          6408  
mean          16866.464414           NaN  
std           18887.576472           NaN  
min             251.000000           NaN  
25%            3447.000000           NaN  
50%            9372.000000           NaN  
75%           24874.000000           NaN  
max          126352.000000           NaN

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27820 entries, 0 to 27819
Data columns (total 10 columns):
sex                   27820 non-null object
age                   27820 non-null object
suicides_no           27820 non-null int64
population            27820 non-null int64
suicides/100k pop     27820 non-null float64
country-year          27820 non-null object
HDI for year          8364 non-null float64
 gdp_for_year ($)     27820 non-null object
gdp_per_capita ($)    27820 non-null int64
generation            27820 non-null object
dtypes: float64(2), int64(3), object(5)
memory usage: 2.1+ MB


In [5]:
obj_data = data.select_dtypes(include=['object']).copy()
obj_data.head()
# вынесла в отдельный датасет данные, которые определяются как категориальные

sex          age country-year  gdp_for_year ($)        generation
0    male  15-24 years  Albania1987      2,156,624,900     Generation X
1    male  35-54 years  Albania1987      2,156,624,900           Silent
2  female  15-24 years  Albania1987      2,156,624,900     Generation X
3    male    75+ years  Albania1987      2,156,624,900  G.I. Generation
4    male  25-34 years  Albania1987      2,156,624,900          Boomers

In [6]:
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
le = preprocessing.LabelEncoder()
ohe = preprocessing.OneHotEncoder()

In [7]:
cat_features = obj_data['age']
enc = preprocessing.LabelEncoder()
enc.fit(cat_features)
new_cat_features = enc.transform(cat_features)
print(new_cat_features) # [1 2 0]

[0 2 0 ... 3 3 4]


In [8]:
new_cat_features = new_cat_features.reshape(-1, 1) # Needs to be the correct shape
ohe = preprocessing.OneHotEncoder(sparse=False) #Easier to read
x = ohe.fit_transform(new_cat_features)
print(x)

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [9]:
x.shape

(27820, 6)

In [10]:
obj_data.shape

(27820, 5)

In [11]:
age_df = pd.DataFrame(x)

In [12]:
age_df.shape

(27820, 6)

In [13]:
age_df.index = obj_data.index

In [14]:
obj_data_age = pd.concat([obj_data, age_df], axis=1)
obj_data_age = obj_data_age.drop(['age'], axis=1)
obj_data_age.head()

sex country-year  gdp_for_year ($)        generation    0    1    2  \
0    male  Albania1987      2,156,624,900     Generation X  1.0  0.0  0.0   
1    male  Albania1987      2,156,624,900           Silent  0.0  0.0  1.0   
2  female  Albania1987      2,156,624,900     Generation X  1.0  0.0  0.0   
3    male  Albania1987      2,156,624,900  G.I. Generation  0.0  0.0  0.0   
4    male  Albania1987      2,156,624,900          Boomers  0.0  1.0  0.0   

     3    4    5  
0  0.0  0.0  0.0  
1  0.0  0.0  0.0  
2  0.0  0.0  0.0  
3  0.0  0.0  1.0  
4  0.0  0.0  0.0

In [15]:
cat_features_2 = obj_data_age['generation']

In [16]:
enc = preprocessing.LabelEncoder()
enc.fit(cat_features_2)
new_cat_features_2 = enc.transform(cat_features_2)
print(new_cat_features_2) # [1 2 0]

[2 5 2 ... 3 3 0]


In [17]:
new_cat_features_2 = new_cat_features_2.reshape(-1, 1) # Needs to be the correct shape
ohe = preprocessing.OneHotEncoder(sparse=False) #Easier to read
y = ohe.fit_transform(new_cat_features_2)
print(y)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 ...
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [18]:
y.shape

(27820, 6)

In [19]:
obj_data_age.shape

(27820, 10)

In [20]:
generation_df = pd.DataFrame(y)

In [21]:
generation_df.index = obj_data_age.index
obj_data_generation = pd.concat([obj_data_age, generation_df], axis=1)
obj_data_generation = obj_data_generation.drop(['generation'], axis=1)
obj_data_generation.head()

sex country-year  gdp_for_year ($)     0    1    2    3    4    5    0  \
0    male  Albania1987      2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
1    male  Albania1987      2,156,624,900  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
2  female  Albania1987      2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
3    male  Albania1987      2,156,624,900  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
4    male  Albania1987      2,156,624,900  0.0  1.0  0.0  0.0  0.0  0.0  1.0   

     1    2    3    4    5  
0  0.0  1.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  1.0  
2  0.0  1.0  0.0  0.0  0.0  
3  1.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0

In [22]:
df = pd.concat([obj_data_generation, data[['suicides_no', 'population', 
                                           'suicides/100k pop', 'gdp_per_capita ($)' ]]], axis=1)
df.head()

sex country-year  gdp_for_year ($)     0    1    2    3    4    5    0  \
0    male  Albania1987      2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
1    male  Albania1987      2,156,624,900  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
2  female  Albania1987      2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
3    male  Albania1987      2,156,624,900  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
4    male  Albania1987      2,156,624,900  0.0  1.0  0.0  0.0  0.0  0.0  1.0   

     1    2    3    4    5  suicides_no  population  suicides/100k pop  \
0  0.0  1.0  0.0  0.0  0.0           21      312900               6.71   
1  0.0  0.0  0.0  0.0  1.0           16      308000               5.19   
2  0.0  1.0  0.0  0.0  0.0           14      289700               4.83   
3  1.0  0.0  0.0  0.0  0.0            1       21800               4.59   
4  0.0  0.0  0.0  0.0  0.0            9      274300               3.28   

   gdp_per_capita ($)  
0                 796  
1                 796  
2                 796  
3                 796  
4                 796

In [23]:
df = pd.get_dummies(df, columns=["sex"])
df.head()

country-year  gdp_for_year ($)     0    1    2    3    4    5    0    1  \
0  Albania1987      2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  Albania1987      2,156,624,900  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
2  Albania1987      2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  Albania1987      2,156,624,900  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0   
4  Albania1987      2,156,624,900  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   

     2    3    4    5  suicides_no  population  suicides/100k pop  \
0  1.0  0.0  0.0  0.0           21      312900               6.71   
1  0.0  0.0  0.0  1.0           16      308000               5.19   
2  1.0  0.0  0.0  0.0           14      289700               4.83   
3  0.0  0.0  0.0  0.0            1       21800               4.59   
4  0.0  0.0  0.0  0.0            9      274300               3.28   

   gdp_per_capita ($)  sex_female  sex_male  
0                 796           0         1  
1                 796           0         1  
2                 796           1         0  
3                 796           0         1  
4                 796           0         1

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27820 entries, 0 to 27819
Data columns (total 20 columns):
country-year          27820 non-null object
 gdp_for_year ($)     27820 non-null object
0                     27820 non-null float64
1                     27820 non-null float64
2                     27820 non-null float64
3                     27820 non-null float64
4                     27820 non-null float64
5                     27820 non-null float64
0                     27820 non-null float64
1                     27820 non-null float64
2                     27820 non-null float64
3                     27820 non-null float64
4                     27820 non-null float64
5                     27820 non-null float64
suicides_no           27820 non-null int64
population            27820 non-null int64
suicides/100k pop     27820 non-null float64
gdp_per_capita ($)    27820 non-null int64
sex_female            27820 non-null uint8
sex_male              27820 non-null uint8
dty

In [25]:
df['country-year'].head()

0    Albania1987
1    Albania1987
2    Albania1987
3    Albania1987
4    Albania1987
Name: country-year, dtype: object

In [26]:
df['country'] = df['country-year'].str.extract('([A-Za-z]+)')
df.head()

country-year  gdp_for_year ($)     0    1    2    3    4    5    0    1  \
0  Albania1987      2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  Albania1987      2,156,624,900  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
2  Albania1987      2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  Albania1987      2,156,624,900  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0   
4  Albania1987      2,156,624,900  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   

    ...       3    4    5  suicides_no  population  suicides/100k pop  \
0   ...     0.0  0.0  0.0           21      312900               6.71   
1   ...     0.0  0.0  1.0           16      308000               5.19   
2   ...     0.0  0.0  0.0           14      289700               4.83   
3   ...     0.0  0.0  0.0            1       21800               4.59   
4   ...     0.0  0.0  0.0            9      274300               3.28   

   gdp_per_capita ($)  sex_female  sex_male  country  
0                 796           0         1  Albania  
1                 796           0         1  Albania  
2                 796           1         0  Albania  
3                 796           0         1  Albania  
4                 796           0         1  Albania  

[5 rows x 21 columns]

In [27]:
df['year'] = df['country-year'].str.extract('(\d+\.?\d*)')
df.head()

country-year  gdp_for_year ($)     0    1    2    3    4    5    0    1  \
0  Albania1987      2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  Albania1987      2,156,624,900  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
2  Albania1987      2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  Albania1987      2,156,624,900  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0   
4  Albania1987      2,156,624,900  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   

   ...     4    5  suicides_no  population  suicides/100k pop  \
0  ...   0.0  0.0           21      312900               6.71   
1  ...   0.0  1.0           16      308000               5.19   
2  ...   0.0  0.0           14      289700               4.83   
3  ...   0.0  0.0            1       21800               4.59   
4  ...   0.0  0.0            9      274300               3.28   

   gdp_per_capita ($)  sex_female  sex_male  country  year  
0                 796           0         1  Albania  1987  
1                 796           0         1  Albania  1987  
2                 796           1         0  Albania  1987  
3                 796           0         1  Albania  1987  
4                 796           0         1  Albania  1987  

[5 rows x 22 columns]

In [28]:
df = df.drop(['country-year'], axis = 1)
df.head()

gdp_for_year ($)     0    1    2    3    4    5    0    1    2  ...     4  \
0      2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...   0.0   
1      2,156,624,900  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   
2      2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...   0.0   
3      2,156,624,900  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  ...   0.0   
4      2,156,624,900  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...   0.0   

     5  suicides_no  population  suicides/100k pop  gdp_per_capita ($)  \
0  0.0           21      312900               6.71                 796   
1  1.0           16      308000               5.19                 796   
2  0.0           14      289700               4.83                 796   
3  0.0            1       21800               4.59                 796   
4  0.0            9      274300               3.28                 796   

   sex_female  sex_male  country  year  
0           0         1  Albania  1987  
1           0         1  Albania  1987  
2           1         0  Albania  1987  
3           0         1  Albania  1987  
4           0         1  Albania  1987  

[5 rows x 21 columns]

In [29]:
mapping = {df.columns[0]:'gdp', df.columns[16]: 'gdp_per_capita'}
df = df.rename(columns=mapping)
df.head()

gdp    0    1    2    3    4    5    0    1    2  ...     4    5  \
0  2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...   0.0  0.0   
1  2,156,624,900  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0  1.0   
2  2,156,624,900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...   0.0  0.0   
3  2,156,624,900  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  ...   0.0  0.0   
4  2,156,624,900  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...   0.0  0.0   

   suicides_no  population  suicides/100k pop  gdp_per_capita  sex_female  \
0           21      312900               6.71             796           0   
1           16      308000               5.19             796           0   
2           14      289700               4.83             796           1   
3            1       21800               4.59             796           0   
4            9      274300               3.28             796           0   

   sex_male  country  year  
0         1  Albania  1987  
1         1  Albania  1987  
2         0  Albania  1987  
3         1  Albania  1987  
4         1  Albania  1987  

[5 rows x 21 columns]

In [30]:
df['gdp'] = df['gdp'].str.replace(',', '').astype(int)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27820 entries, 0 to 27819
Data columns (total 21 columns):
gdp                  27820 non-null int64
0                    27820 non-null float64
1                    27820 non-null float64
2                    27820 non-null float64
3                    27820 non-null float64
4                    27820 non-null float64
5                    27820 non-null float64
0                    27820 non-null float64
1                    27820 non-null float64
2                    27820 non-null float64
3                    27820 non-null float64
4                    27820 non-null float64
5                    27820 non-null float64
suicides_no          27820 non-null int64
population           27820 non-null int64
suicides/100k pop    27820 non-null float64
gdp_per_capita       27820 non-null int64
sex_female           27820 non-null uint8
sex_male             27820 non-null uint8
country              27820 non-null object
year                 278

In [32]:
df.country.value_counts()

United         816
Saint          672
Austria        382
Netherlands    382
Mauritius      382
Iceland        382
Ecuador        372
Puerto         372
Belgium        372
Malta          372
Mexico         372
Brazil         372
Colombia       372
Singapore      372
Chile          372
Israel         372
Japan          372
Luxembourg     372
Republic       372
Greece         372
Argentina      372
Spain          372
Italy          372
Costa          360
Norway         360
France         360
Bulgaria       360
Guatemala      360
Australia      360
Ireland        360
              ... 
Lithuania      262
Switzerland    252
Belarus        252
Bahrain        252
Latvia         252
Estonia        252
Slovenia       252
South          240
Seychelles     216
Serbia         216
Jamaica        204
Azerbaijan     192
Philippines    180
Cyprus         178
Qatar          178
Aruba          168
Kiribati       132
Sri            132
Fiji           132
Montenegro     120
Maldives       120
Turkey      

In [33]:
threshold = 100
counts = df.country.value_counts()

In [34]:
freq = counts[counts <= threshold].index
countries = pd.get_dummies(df.country.replace(freq, 'uncommon'))
countries.head()

Albania  Antigua  Argentina  Armenia  Aruba  Australia  Austria  \
0        1        0          0        0      0          0        0   
1        1        0          0        0      0          0        0   
2        1        0          0        0      0          0        0   
3        1        0          0        0      0          0        0   
4        1        0          0        0      0          0        0   

   Azerbaijan  Bahamas  Bahrain    ...     Sweden  Switzerland  Thailand  \
0           0        0        0    ...          0            0         0   
1           0        0        0    ...          0            0         0   
2           0        0        0    ...          0            0         0   
3           0        0        0    ...          0            0         0   
4           0        0        0    ...          0            0         0   

   Trinidad  Turkmenistan  Ukraine  United  Uruguay  Uzbekistan  uncommon  
0         0             0        0       0        0           0         0  
1         0             0        0       0        0           0         0  
2         0             0        0       0        0           0         0  
3         0             0        0       0        0           0         0  
4         0             0        0       0        0           0         0  

[5 rows x 89 columns]

In [35]:
countries.shape

(27820, 89)

In [36]:
df = pd.concat([df, countries], axis=1)
df.head()

gdp    0    1    2    3    4    5    0    1    2   ...     Sweden  \
0  2156624900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   ...          0   
1  2156624900  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   ...          0   
2  2156624900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   ...          0   
3  2156624900  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   ...          0   
4  2156624900  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   ...          0   

   Switzerland  Thailand  Trinidad  Turkmenistan  Ukraine  United  Uruguay  \
0            0         0         0             0        0       0        0   
1            0         0         0             0        0       0        0   
2            0         0         0             0        0       0        0   
3            0         0         0             0        0       0        0   
4            0         0         0             0        0       0        0   

   Uzbekistan uncommon  
0           0        0  
1           0        0  
2           0        0  
3           0        0  
4           0        0  

[5 rows x 110 columns]

In [37]:
df = df.drop(['country'], axis = 1)
df = df.drop(['year'], axis = 1)

In [38]:
X = df.loc[:, df.columns != 'suicides/100k pop']
y = df['suicides/100k pop']
X.head()

gdp    0    1    2    3    4    5    0    1    2    ...     Sweden  \
0  2156624900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0    ...          0   
1  2156624900  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    ...          0   
2  2156624900  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0    ...          0   
3  2156624900  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0    ...          0   
4  2156624900  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0    ...          0   

   Switzerland  Thailand  Trinidad  Turkmenistan  Ukraine  United  Uruguay  \
0            0         0         0             0        0       0        0   
1            0         0         0             0        0       0        0   
2            0         0         0             0        0       0        0   
3            0         0         0             0        0       0        0   
4            0         0         0             0        0       0        0   

   Uzbekistan  uncommon  
0           0         0  
1           0         0  
2           0         0  
3           0         0  
4           0         0  

[5 rows x 107 columns]

In [39]:
scaler = preprocessing.StandardScaler()
scaler.fit(X)
X_new = scaler.transform(X)

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=30)

In [41]:
X_train.shape, X_test.shape

((22256, 107), (5564, 107))

In [42]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

estimator = LinearRegression()
estimator.fit(X_train, y_train) # Обучение


y_pred = estimator.predict(X_test)

print("R2: \t", r2_score(y_test, y_pred))
print("RMSE: \t", np.sqrt(mean_squared_error(y_test, y_pred)))
print("MAE: \t", mean_absolute_error(y_test, y_pred))

R2: 	 0.543662826450727
RMSE: 	 12.695543647677791
MAE: 	 8.225937644148894
